#!/bin/sh
'''exec' "/Users/nagaokeisuke/Desktop/KINGS Group/sokuhime_line_bot/venv/bin/python3.13" "$0" "$@"
' '''
import sys
from libfuturize.main import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
