name: update
on:
  workflow_dispatch:
  jobs:
    run:
        runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v4
                        - run: python cityheaven_updater.py
                                env:
                                          CITYHEAVEN_ID: ${{ secrets.CITYHEAVEN_ID }}
                                                    CITYHEAVEN_PW: ${{ secrets.CITYHEAVEN_PW }}
                                                              LOGIN_URL: ${{ secrets.LOGIN_URL }}
                                                              
